import { createSlice } from '@reduxjs/toolkit';

const cartSlice = createSlice({
  name: 'cart', // Name of the slice
  initialState: {
    items: [], // Initial state contains an empty cart
  },
  reducers: {
    // Action to add an item to the cart
    addToCart: (state, action) => {
      const existingItem = state.items.find(item => item.id === action.payload.id);
      if (existingItem) {
        // If item already exists, increase its quantity by 1
        existingItem.quantity += 1;
      } else {
        // If item does not exist, add it to the cart with quantity 1
        state.items.push({ ...action.payload, quantity: 1 });
      }
    },
    
    // Action to remove an item from the cart
    removeFromCart: (state, action) => {
      state.items = state.items.filter(item => item.id !== action.payload); // Filter out the item with the provided ID
    },
    
    // Action to update the quantity of an item in the cart
    updateQuantity: (state, action) => {
      const { id, quantity } = action.payload;
      const item = state.items.find(item => item.id === id);
      if (item) {
        item.quantity = quantity; // Update the quantity of the item
      }
    },
  },
});

// Exporting the actions generated by createSlice
export const { addToCart, removeFromCart, updateQuantity } = cartSlice.actions;

// Exporting the reducer function to be used in the store
export default cartSlice.reducer;
